### ISSUE TITLE
Work permit

### ISSUE THREAD

**Issue by paulorely** [edenspiekermann/ama#10]
Do edenspiekermann provide work permit for non-EU employees? :)

**Comment by sdietrichberlin** [comment]
Hey Paul, yes we have done this in the past and will in the future. But it's a case-by-case decision, not a general rule. Keep in mind this is a rather gruesome process to apply for a blue card and the outcome isn't always certain. Send us your application and we'll have a look.

**Comment by paulorely** [comment]
Thanks for the answer, Sebastian!
