### ISSUE TITLE
Any advise you can give to Graphic Design students?

### ISSUE THREAD

**Issue by enerrro** [edenspiekermann/ama#11]
Hello, I am a Graphic Design student from California State University Long Beach. I am doing a presentation about Erik Spiekermann for my History of Graphic Design class. I would like to see what you guys have learned from the man himself or if there is anything you would like to say to us aspiring Graphic Designers? Thank you!

**Comment by martzoukos** [comment]
“Use the right quote marks.”

Every. Effing. Time.

**Comment by EdoCH** [comment]
Here are some of my favourite quotes. Some of them have been guiding principles for me for many years. 

Design is not just what it looks like and feels like. Design is how it works.
- Steve Jobs

There is a crack in everything, that is how the light gets in.
- Leonard Cohen

Creativity is allowing yourself to make mistakes. Design is knowing which ones to keep.
- Scott Adams

If you pay peanuts, you get monkeys.
- James Goldsmith

Don't work for assholes. Don't work with assholes.
- Erik Spiekermann

**Comment by EdoCH** [comment]
Also: check our manifesto which was predominantly written by Erik. It's on our website.

**Comment by christianhanke** [comment]
An interview which struck me and is so encouraging with Eddie Opara! 
Q: what advice do you have for young designers?
A: Don’t be scared. To say what you think, to restructure something, to take the lead. Just don’t be afraid.
http://www.printmag.com/interviews/a-cup-of-coffee-with-pentagrams-eddie-opara/

**Comment by enerrro** [comment]
Thank you everyone for your comments! These are all helpful and I will definitely mention them during my presentation. 

@martzoukos I will make sure to pay attention to those quote marks.

@EdoCH I will make copies of these quotes and give them to my classmates. Your manifesto is awesome!

@christianhanke The Eddie Opara Print Mag interview was very insightful.

Thanks again!

**Comment by heretakis** [comment]
You must work to develop Hand/Heart?Eye coordination. Drawing skills together with photography is essential in developing to Look not just see.
