### ISSUE TITLE
What are some of your favorite typefaces?

### ISSUE THREAD

**Issue by scottjraney** [edenspiekermann/ama#12]
I know it is so hard to pick just one, so maybe you can list a few instead. What are some of your favorite typefaces?

**Comment by smartmike** [comment]
Helvetica

**Comment by HugoGiraudel** [comment]
When it comes to monospace typefaces, we (I?) do like [Fira](https://github.com/mozilla/Fira) from Mozilla but designed by Erik Spiekermann. :)

**Comment by mguth** [comment]
Sorry, but I can’t really answer your question – at least not in the form of specific names.

But I can say one thing: We pick whatever typeface fits the projects needs, character and context best. We do not have a regularly re-used shortlist of favourites but rather choose on a per-project-basis.
