### ISSUE TITLE
Why is the wind free ?

### ISSUE THREAD

**Issue by lipsumar** [edenspiekermann/ama#13]
Nobody ever asked me to pay for the wind. Why is that ?

**Comment by HugoGiraudel** [comment]
![WTF](https://media.giphy.com/media/rQPRCclTBVyU0/giphy.gif)

**Comment by martzoukos** [comment]
Wind is not free, my friend.
https://www.wind.gr/en/

**Comment by peterjmag** [comment]
This is my favorite AMA question.

**Comment by mattcav** [comment]
It offers very convenient fares in Italy: http://www.wind.it/it/privati/
