### ISSUE TITLE
Could you please describe in detail the second method to setup multi-tenant site

### ISSUE THREAD

**Issue by jaswinder97** [edenspiekermann/ama#16]
I have gone through your blog http://dev.edenspiekermann.com/2016/09/09/rails-multitenant-site/ for referencing the second method to setup.But it doesn't have full details .Could you please create a new blog with full setup step by step--the second method i.e without scoping

**Comment by nburkley** [comment]
Hi @jaswinder97 - are you asking about setting up a multi-tenant site without out scoping the data in the database? 

The [blog post](http://dev.edenspiekermann.com/2016/09/09/rails-multitenant-site/) outlines the approach we took to create a multi-tenant site - for the project in question, we decided that scoping the data using PostgreSQL schemas would work best. 

If you're looking for details on how to doing this without PostgreSQL schemas you'll need to use `default_scope`s. 

Here's a good Railscast outlining this approach: http://railscasts.com/episodes/388-multitenancy-with-scopes. There's a gem [acts_as_tenant](https://github.com/ErwinM/acts_as_tenant) that helps make the setup easier: https://github.com/ErwinM/acts_as_tenant. 

Hope that helps.

**Comment by jaswinder97** [comment]
I am getting an error while adding tenants via site-settings yml.

`One of the following schema(s) is invalid: "alpha" "public"`
