### ISSUE TITLE
On ditching the pitch

### ISSUE THREAD

**Issue by RyanRoberts** [edenspiekermann/ama#4]
Hi,

I've just read your article on [clients ditching the pitch](http://www.edenspiekermann.com/blog/clients-who-dare-ditching-the-pitch) and shared it with others in our office. We have a couple of questions:

- Did you and the others get paid for your time?
- Do you think you would have loved the process as much had your lost out to another company in the end?

Thanks!

**Comment by JonneKuyt** [comment]
Hi, 

There was reasonable cost covering for very agency for the one day session.

If you don’t include the possibility of losing you should never be in any competition. We said yes to part of the competition with the goal of winning. But we did not have to play a long game in the dark. The transparant process and framework of the assignment made the investment of time and resources reasonable. And more importantly there was no reason to blame the process in case we lost. We were able to see and judge other agencies work and would have accepted the fact we were outperformed by the others.

**Comment by RyanRoberts** [comment]
Thanks Jonne!
