### ISSUE TITLE
What's a typical day like at Edenspiekermann?

### ISSUE THREAD

**Issue by scottjraney** [edenspiekermann/ama#5]
You know, when do you arrive at the office? When do you leave? And what happens in the middle?

**Comment by smartmike** [comment]
My standard day:
9:20: Arrive. Drink coffee.
9:30: First project daily. More coffee.
10:00: Second project daily. Another coffee.
13:00ish: Lunch, out of the office usually at a restaurant, or when it's sunny in the park just around the corner. Maybe a Club Mate to fight the coffee urge.
14:00ish: Back to work. More coffee.
18:00-18:30: Quitting time. No more coffee.

In between these times, sometimes I code, sometimes I talk to people, sometimes I'm deep in a google doc, and sometimes I'm talking with clients.

**Comment by HugoGiraudel** [comment]
Hey! That’s an interesting question. Thanks for asking, Scott.

I guess a typical day depends on the position at Edenspiekermann. A designer, a people & talent director, and a back-end developer probably do not have the same day! Although I suppose we all more or less share the same rhythm, so I will try to share my thoughts on the matter. Fair warning: it might be a developer-centric standpoint.

The day starts between 8AM and 10AM, depending on the persons, the day of the week, the mood, the amount of work and all the usual factors. No matter at what time you arrive in the office in this time span, there will be someone in the kitchen making coffee (or tea, but that’s less common). The smooth noise of the coffee beans being milled and the milk becoming foaming is so typical here. Some people even enjoy to take their breakfast here, as we have everything to have a perfect day-starter. Nothing better than starting the day with a massive bowl of sliced fresh fruits with muesli and milk (especially when you woke up late and didn’t have time to have breakfast at home), am I right?

At 10AM, it is the daily scrum for most teams. At Edenspiekermann, we heavily rely on [Agile](https://en.wikipedia.org/wiki/Agile_software_development) and [Scrum](https://en.wikipedia.org/wiki/Scrum_(software_development)) methodologies to work with our clients. Every morning once everybody’s here with the decent amount of cafeine in the blood, we gather around the physical board of the project (a very large board or actual wall where we pin and write stuff) and tell what we did the day before and what we are planning on doing during the day. Members of the teams that are not here (home-office, business trip, remote working, etc.) join us on Skype / Hangouts or whatever is the tool that works best for video chat (hint: none, they all are terrible most of the time). The daily usually takes no more than 10 minutes. It is not a full blown meeting; the point is only to keep the team up-to-date, not to discuss profound issues and technical solutions.

After the daily, the day can start for good. Everybody gains their seat and starts working on whatever they have to do. Some people prefer working at their desk. Some people prefer working on the couch. Some people have music in the ears, some people don’t. It’s up to anyone to work in the way they prefer, as long as the job gets done. The open-spaces are pretty quiet at this time of the day, but there are always a few people talking to each others. Developers do some pair-programming, designers work with developers, and all in all people enjoy working with each others.

At around noon, people start leaving for lunch. Or heating the lunch they brought. We have a huge and beautiful wooden kitchen where people can sit together and enjoy the lunch break. Between noon and 2PM, people come and go to grab something to eat. The open-spaces are silent, the kitchen is noisy. Some people take their lunch break much later, like at 2PM or even 3PM. Some people like me (maybe only me?) sometimes do not take a lunch break at all to work on something else, and enjoy the quietness of the rooms.

In the early afternoon, the coffee machine is heavily used again. It’s the after-lunch coffee. Everybody gets back to work after the lunch break, so between 1PM and 2:30PM, mostly. The afternoon is usually quite peaceful. I believe for most people it’s the productivy peak. It is for me, at least. We often see people grabbing a drink in the storage during the afternoon: Club Mate, Fritz Cola, apple juice, there’s a beverage for everyone! It goes on until 5PM or so where some people start to leave. From this point on, the office gets more empty every hour. I also noticed that at this moment of the day, some people like to gather to discuss about what’s been done or what are the encountered problems, in a very informal way. We often see more people in the couch at the end of the day than in the morning.

Between 6:45PM and 8PM usually, the office is more silent than ever. The last person to leave closes the office and go. Then, the walls and the coffee machine can enjoy a few quiet hours before seeing us coming back the next day. :)

**Comment by mattberridge** [comment]
As I'm not such a 'morning' person my morning always begins with arriving just in time (ahem) for my current project's daily standup meeting! Pretty much every Espi employee always works under an [agile process called Scrum](http://www.edenspiekermann.com/blog/the-agile-agency) which means a project is divided into two week (*sprints*) of work, and short *daily* meetings every morning with the project team and product owner to discuss yesterdays progress and plan the day ahead. These are meant to be informal and often take place at one of our magnetic-blackboard planning walls which we have all around the office.

![img_2122](https://cloud.githubusercontent.com/assets/447493/9404407/b71cb1f2-47ef-11e5-9f1c-b3badf355be1.JPG)

These daily meetings are any time between 9:15 - 10:00am depending on the project and as long as I make it here in time for that, it's all good. Other people come in earlier and leave earlier (say 17:00) but I find my best working hours between 16:00 - 19:00 so am always one of the last to leave! It's totally flexible and I'm trusted to manage my own time. It's frowned upon to work late into the evening and usually the office is locked around 7pm and you'll have to go home.

Thursday morning is slightly different – we always have a company event called *Brainfood* – with a 30 minute external or internal presentation and provided buffet breakfast. Lunch is never typical - some days I don't eat, others we're at a restaurant nearby with the whole team, sometimes I just go for a walk or listen to music.

During the day you're 100% in control of your own working process and environment. We are mostly situated in desks of 6 per-project but have other quiet working areas if you wish. You can also take as much time away from your desk as you want to sit at the couches to relax a bit, form a group for discussion or co-working, play video games or table tennis. 

A workday *always* involves working on the user stories you said you'd be taking care of at daily with no distractions of anyone asking you to work on anything else - something I value a lot and the beauty of the Scrum process. It also always involves everyone working inter-disciplinary and solving problems together without a manager telling you what to do; you're always trusted entirely to get your work done with few boundaries other than that. This means colleagues are always open to questions or sitting together and pair-programming, but you know when you've got time and when you haven't!

And of course, it wouldn't be a typical day without one of the admin team dropping at least one record that has been delivered off ay my desk ;)

**Comment by scottjraney** [comment]
Wow, thanks for the detailed responses. That was super interesting!
