### ISSUE TITLE
Semis or not?  ;)

### ISSUE THREAD

**Issue by backspaces** [edenspiekermann/ama#7]
Sorta semi serious, after reading 
https://github.com/feross/standard#javascript-standard-style 
and using it for a webgl project along with babel/es6 and jspm. Free at last!

**Comment by artibella** [comment]
We usually use semi colons in our JS, but the coding standards are decided by the project teams – see also #3. I, personally stick with them out of old habits and don't want to take care about the edge cases when semi colons are needed or not.

**Comment by HugoGiraudel** [comment]
We do use semi-colons. Everywhere, every time, no exception. :)
